## db configs
runmode="debug"
name = "apiservice"
addr=":8088"
port=8848
max_ping_count=10

[pg]
dbname = "gin"
user = "postgres"
passwd = "123456"
port = 30003
host ="postgres.cfwd.com"
poolsize=10

[mongo]
dbname="cfwd"
host="mongo.cfwd.com"
port="30001"
passwd="cfwdpwd"
user="cfwdusr"
poolsize=10
usereplicaset=true
replicasetconn="dds-2ze7e06287a540d41.mongodb.rds.aliyuncs.com:3717,dds-2ze7e06287a540d42.mongodb.rds.aliyuncs.com:3717/admin?replicaSet=mgset-7405193"

[redis]
host="redis.cfwd.com"
port="30002"
passwd=""
db=0
poolsize=100

[mqtt]
wsuri="ws://mqtt.cfwd.com:80"
wssuri="wss://mqtt.cfwd.com:443"
clientid="server-publish"
username="admin"
password="123456"

[log]
path="/var/web/gin/logw"

[qiniu]
  ak="5kvHZAUPKAM8iaPFfx0DWI1yyxUm7DkpqfNfK540"
  sk="n1qUXBzWrKQnfWWoeMoWm45nP7NwJRf_xKVNM99a"

[wechat]

    [wechat.applets]
    appid="wxc1b28e67dc962984"
    secret="eb3e3b585b13fe57624983c0dd088bc5"

    [wechat.gzh]
    appid="wx1b05daceff0cadbf"
    secret="32aa59d6dea5616af445461d38b1b7ce"

    [wechat.open]
    appid="wx1d20ce3cb97d27a5"
    appSecret="2fe02da2af551712b6fe2343b2611c7a2"
    redirect_uri="cfwd.com/auth/wechat/callback"

    [wechat.pay]
    mchid="1487206792"
    apikey="363f301726964df09f47b91e6e258bfc"
    WECHAT_NOTIFY_URL="https://www.cfwd.com/api/v1/pay/wx/return"
    pkcsPwd=""
    
ase="astaxie12798akljzmknm.ahkjkljl;l"
hmacSha256="5b13fe597d2xc1b28e258b"

[gzhServer]
  url="183.69.224.33"
  oriId=""
  token="T0Vxv2aQf6zU1zy9aInViqyivod"
  encodingAESKey="T0Vxv2aQf6zU1zy9aInViqyivodBqa4A5mxISPmdkHB"

[elastic]
  addr="es-cn-4590xmo630002nnhu.public.elasticsearch.aliyuncs.com"
  port="9200"
  username="elastic"
  password="Koumin917"

[alipay]
  appid="2018101161675098"
  publicKey="MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAxh06ZgZRwCW1p9WoT+36xwCMAfp8QVCBmIA1rFflqrfguu+Z21U2/TIDAKsdXyJbmU0mezi8pBX29AUZ0PAVcOHQbZJOPYWa31VSwCqdZNBAL3ib7vcg5Qzz2qoFBtA6ui/6RP8u7N5m5HciLTOFmTUeDMG5WLA3Y/YMeKam9nPA8rpoAKFcyO6NF/KqwcocbsRhlOW56Dg4e8TO/SR/iQsrnnGzW0ndT1452utnDL1C5wmdggnZka8PA8BIp0FPNw7UWayqoYue209pAEs97lwCAsbi+S3OLU4RwaNtPPRT9Fc4GbllQF4Lb3i+lVMcMO6yOPb7yhcAvqVaL62hWQIDAQAB"
  privateKey="MIIEpAIBAAKCAQEA4nke2KZAMNPC7Z4I7mJiA8kC0WmWKskzJ0keHFgrvJyfcrAazp1XB0wqbJ61/MPar5KQLV6uFbmU4hGc22kdVhpVLTqSaxWqFIa3rpd6cAT1VSoukC3UHLrVHAk4ubd2rKAtL4uKpL6SMhcyrWs6xb6yq148OPHLLEYv0BDs9K3sJAQh92Her0I8Avdh2piymXPxrIwshZLj9pG8N4h7RcJUB/IuvlfiNVXHByU/+0hTzIyb6T+9VYBWfiMoviNiFulWJW0pkPrKyOauKn+RYuGr7KsxlOJIsp1Dt/K5XpQF4/Ej1WoB4ONgR8+/C4OCKJCwCw8jqLt1YxHogjZtxQIDAQABAoIBAEF/miY6XtJATF4AmMCo/4PsvL3n9aBGNF8mTGkSLwQLoCnBON+MrcDUjGiBtkx2MGca0kvs2Bg8ZgzD30OtsOhYEU5VZEdIKrppA/KgqK6BIJsS6giU2IW+myfSmu9LWi0u3iKkDuL6ormN8AArxQGv12ishmpJs+MIIYfhfUZ+Az4rKkxmcWPoAhV4eBDBjjbEBxtEgqFSfd1JbOXKTdHfy90HLI0EEuVbg2qPYr6AsGxdm6n8BeICMqEwVeSKpyvkB4JbU/RRac9aHDHTFYuBOxuQ0V/P6xJhszEhU08ZbQSOys1jMinOz0VM2Fr6vdcpicM3TrrHsasjr50ZLrkCgYEA9rbrH/bB44MNtrb5pyRAszLYnuNAv/aJcmvZPk8UKScc5TCGcH2Oqiovvw33k0sx+02gQz4CD9Bv4j4yd3qqoVdlCYI+4BQPmvNcQuQZS1q7FvBF4h3XRzxCekjqkXWXkGUPh5aG/vMMiaoeFntMyXGVJee3p3Q7YfwcpYQEYPcCgYEA6v8tXoAB0v/+TmMNdQC3CuB8LexjrtLFDuTtB3e2wB0A7cNq24Fdd1eW03WkdYd+qA+oPyyi5X1kPTS+bx/cir4DzsecFvqXM9JasZAnc0watxC12Yu3oeMY/VBkc91AsQ8a4tPcuTmEDoEBPiKpg8VjhrlpBGb7P3nLb42tNCMCgYA7xtArW3dY75z4A1dz9uWyRYSU4s0CdfKRha4KWdCxs+ddZKd+Q/24HyaYbQLqblK65/EHudN4D3G8aIODzXXgR7OUXTlsw4+QZJybHHdAechQ44CbK83IVcJprJchDVPeyY28tW0aArur80r8+Xz+ZgXUPFOUQCZPNG2gcN86uwKBgQDB+BUrzn8y+eigLTR7Yja0PK1jfp6dPA46CA36Pv9Svd35Y3b9bl+G1X6CVrWD6W5LLHlUg/SFdqXZu4KA2QzCXKtp7+tQMFHEDZqcu/9ENQpMFvfzdFcDwh7rYIM5++OdAnnPxs6G+Qmeqy8qaZQAV1qaZspfPt2d/FtGXewcfwKBgQDYnHed3pOHl4dm2DZDg7E+m22cWzj5Lc8j2ev7KthOJb84Zh7EmmRMvx4cBAVJM8+5jmReVk8QJ+SbXNqzGC2RTaL9yKvcyFJ+qoDQk1oOSIm3G3Mr08X9GuAc5SF7hXxpXxZQug28XMrXZhnZWo3AauupAkfD1NeMmmtgVMsBcg=="
  notifyUrl="https://www.cfwd.com/api/v1/pay/alipay/notify"
  returnUrl="https://www.cfwd.com/api/v1/pay/alipay/return"

[sms]
  vid="5c209309fc650e4c884c8146"
  smskey="2cfda553e0434d3d9cad379d963288b3"
    tid="1"

[certificate]
    [certificate.wechat]
        certFileRoute="conf/wechat/apiclient_cert.pem"
        keyFileRoute="conf/wechat/apiclient_key.pem"