## db configs
runmode="debug"
name = "apiservice"
addr=":8088"
port=8848
max_ping_count=10
[pg]
dbname = "gin"
user = "postgres"
passwd = "123456"
port = 5432
host ="192.168.0.2"
poolsize=10

[mongo]
dbname="cfwd"
host="192.168.0.2"
port="27017"
passwd="cfwdpwd"
user="cfwdusr"
poolsize=10

[redis]
host="192.168.0.2"
port="6379"
passwd=""
db=0
poolsize=100

[mqtt]
wsuri="ws://mqtt.cfwd.com:80"
wssuri="wss://mqtt.cfwd.com:443"
clientid="server-publish"
username="admin"
password="12345678"

[log]
path="/var/web/gin/logw"

[qiniu]
  ak="5kvHZAUPKAM8iaPFfx0DWI1yyxUm7DkpqfNfK540"
  sk="n1qUXBzWrKQnfWWoeMoWm45nP7NwJRf_xKVNM99a"

[wechat]

    [wechat.applets]
    appid="wxc1b28e67dc962984"
    secret="eb3e3b585b13fe57624983c0dd088bc5"

    [wechat.gzh]
    appid="wx1b05daceff0cadbf"
    secret="32aa59d6dea5616af445461d38b1b7ce"

    [wechat.open]
    appid="wx1d20ce3cb97d27a5"
    appSecret="2fe0da2af551712b6fe2343b2611c7a2"
    redirect_uri="cfwd.com/auth/wechat/callback"
    
    [wechat.pay]
    mcid="1487206792"
    apikey="363f301726964df09f47b91e6e258bfc"
    WECHAT_NOTIFY_URL="https://www.cfwd.com/pay/wx/return"
    
ase="astaxie12798akljzmknm.ahkjkljl;l"
hmacSha256="5b13fe597d2xc1b28e258b"

[gzhServer]
  url="183.69.224.33"
  oriId=""
  token="T0Vxv2aQf6zU1zy9aInViqyivod"
  encodingAESKey="T0Vxv2aQf6zU1zy9aInViqyivodBqa4A5mxISPmdkHB"

[elastic]
  addr="elastic.cfwd.com"
  port=30006

[alipay]
  appid="2018101161675098"
  publicKey="MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA5EMJGTIM5EzyliVccMW8F+kkexDIBb9dFdEXIg1WvKrHW0HCPPz7Kx+iz9rquySi59nZ/Jwfx8D52NBNdA99heJXhu/BdLYtHdwS7h8Jm3WrAW6+xZ/n0W9WVYU7zGOl3wz+JZQZVY7FXAqWmccuPJllPyhTNHpe/vdCtwnwvzNCYiupahvlzgwr1XkpjxSPShrLEcbJqM84yre92QdjIxY/DurYOQ39wbMkFUWnkdtIYZPN0ALZrt7436e4JwwgVTTkCkFELJZ/RVZdsf7yNUx+lSLGnCFVRzwseyEalc/lBXAtsG/WtmiqhKSI8PUamitURipFoB6V8sN5qJXBdQIDAQAB"
  privateKey="32jM6iBLeXpI/YCw+vxs6g=="
  notifyUrl="https://www.cfwd.com/api/v1/pay/alipay/notify"
  returnUrl="https://www.cfwd.com/api/v1/pay/alipay/return"
[sms]
  vid="5c209309fc650e4c884c8146"
  smskey="2cfda553e0434d3d9cad379d963288b3"